<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-BlogCore-bd7c8c4e-6368-4bd4-b320-d058231d2afa</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Areas\Admin\**" />
		<Compile Remove="Areas\Cliente\**" />
		<Content Remove="Areas\Admin\**" />
		<Content Remove="Areas\Cliente\**" />
		<EmbeddedResource Remove="Areas\Admin\**" />
		<EmbeddedResource Remove="Areas\Cliente\**" />
		<!--<None Remove="Areas\Admin\**" />
    <None Remove="Areas\Cliente\**" />-->
	</ItemGroup>

	<ItemGroup>
		<Compile Include="Areas\Admin\Controllers\ArticulosController.cs" />
		<Compile Include="Areas\Admin\Controllers\CategoriasController.cs" />
		<Compile Include="Areas\Admin\Controllers\SliderController.cs" />
		<Compile Include="Areas\Cliente\Controllers\HomeController.cs" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Areas\Admin\Views\_ViewImports.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="Areas\Admin\Views\_ViewStart.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="Areas\Cliente\Views\Home\Index.cshtml" />
		<Content Include="Areas\Cliente\Views\Home\Privacy.cshtml" />
		<Content Include="Areas\Cliente\Views\_ViewImports.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Include="Areas\Cliente\Views\_ViewStart.cshtml">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Datos.BlogCore\Datos.BlogCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Areas\Admin\Views\Categorias\Index.cshtml" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Areas\Admin\Views\Categorias\Create.cshtml" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Areas\Admin\Views\Categorias\Edit.cshtml" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Areas\Admin\Views\Articulos\Create.cshtml" />
		<Content Include="Areas\Admin\Views\Articulos\Edit.cshtml" />
		<Content Include="Areas\Admin\Views\Articulos\Index.cshtml" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\imagenes\articulos\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Areas\Admin\Views\Slider\SliderIndex.cshtml" />
	</ItemGroup>

</Project>

